repos:
-   repo: https://github.com/gitleaks/gitleaks
    rev: v8.16.4
    hooks:
    -   id: gitleaks
-   repo: https://github.com/psf/black
    rev: 22.10.0
    hooks:
    -   id: black
-   repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
    -   id: isort
        args: ["--profile", "black", "--filter-files"]
-   repo: local
    hooks:
    -   id: config-files-check
        name: Checking Config file changes
        entry: .github/hooks/pre-commit.sh
        language: script
    -   id: eslint
        name: ESLint
        entry: web/node_modules/.bin/eslint --fix
        language: system
        files: ^web/
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
